[project]
name = "renovate-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Glyn Mooney", email = "749058+skidoosh@users.noreply.github.com" }
]
requires-python = ">=3.14.0"
dependencies = [
    "fastapi==0.18.0",
]

[project.scripts]
python = "python:main"

[[tool.uv.index]]
name = "artifactory"
url = "https://artefacts.tax.service.gov.uk/artifactory/api/pypi/pips/simple/"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
exclude-newer="72 hours"
package = false
no-binary-package = ["starlette"]

[dependency-groups]
dev = [
    "diskcache==5.6.3",
    "ruff==0.15.0",
    "ty==0.0.71",
]
